# Generated by Django 4.2.2 on 2023-06-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_postmodel_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-date_created']},
        ),
    ]
